import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Royle ZamaLuxe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
  
          <div className="overflow-x-hidden">
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </div>
      </body>
    </html>
  );
}
